version: "3"
services:
  database:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=demo
      - POSTGRES_USER=demo_user
      - POSTGRES_PASSWORD=demo_pass
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/posgresql/data

volumes:
  db-data: